### ISSUE TITLE
Remove half steps?

### ISSUE THREAD

**Issue by SparklePigBang** [sacktock/SGHMC#14]
In the paper, and other papers I've read which give related algorithms, they don't do the half step before and after. Probably because the noise messes things up. Shall we get rid of it in our implementation?

**Comment by sacktock** [comment]
We should evaluate the difference of having / not having half steps before removing it but yeah I agree that it probably makes sense to get rid of it

**Comment by SparklePigBang** [comment]
If we do that, we can remove all the `step_size` parameters from our method signatures, which should declutter things a bit

**Comment by sacktock** [comment]
Yeah I'm doing this now

**Comment by sacktock** [comment]
I've done it and found a bug along the way which is fixed now, sampling is better but its broekn my automatic step size adjustment so I'll push once if fixed it
