### ISSUE TITLE
Friction is getting added to position

### ISSUE THREAD

**Issue by SparklePigBang** [sacktock/SGHMC#3]
From what I can tell from the code, it looks like the friction noise is being added to both the momentum and the position, because it is being introduced in [`_step_variable`](https://github.com/sacktock/SGHMC/blob/64c03ab31d9ec1a4805be3e367b69e9c0783dc0d/sghmc.py#L90), which is applied to both position and momentum.

In the paper, it's only added to momentum.

**Comment by sacktock** [comment]
Yep you're right looks like your pull request has fixed it.

**Comment by SparklePigBang** [comment]
Actually, I didn't change anything about this. I think it's still being added to both

**Comment by sacktock** [comment]
Ok I'll fix it and push tonight
