### ISSUE TITLE
TODO: allow arbitrary args and kwargs to be pased to the model

### ISSUE THREAD

**Issue by sacktock** [sacktock/SGHMC#5]
At the moment any model args and kwargs are ignored, so only models with one argument - the data, are going to work. We may want to set hyper priors / parameters and pass them as arguments later on so I will fix this

**Comment by SparklePigBang** [comment]
Yeah, and another thing is that the data is passed to the SGHMC constructor, while in the Pyro implementations model arguments are passed instead to the `run` method, which in turn calls `setup`.
