### ISSUE TITLE
TODO: implement automatic step size / automatic num step 

### ISSUE THREAD

**Issue by sacktock** [sacktock/SGHMC#6]

**Comment by SparklePigBang** [comment]
Are you working on this? If not I'm happy to have a look

**Comment by sacktock** [comment]
I'm going to have a go today, but feel free to look into it I will likely need some help

**Comment by SparklePigBang** [comment]
Okiedokie. We can create a separate branch here and work on it there. How were you thinking of doing it?

**Comment by sacktock** [comment]
Not really sure now I look at it the pyro way is to choose a step size so that some target acceptance probability is matched, but with SGHMC we don't have MH correction so this makes it a little less straightforward.

**Comment by SparklePigBang** [comment]
I guess we could compute the acceptance probability for the minibatch potential function? Might be worth seeing how it changes things at least

**Comment by sacktock** [comment]
Yeah this might do something

**Comment by sacktock** [comment]
Closing for now since this is sort of done

**Comment by sacktock** [comment]
Still need to work on this a bit

**Comment by sacktock** [comment]
Its as good as its going to get so I'm closing this
