### ISSUE TITLE
Why do we only work with the first model argument?

### ISSUE THREAD

**Issue by SamAdamDay** [sacktock/SGHMC#9]
I don't quite see why we only work with the first argument to the model. The other arguments should still be part of the data, I think. For example, the model could take x and y, i.e. input and output. In the Pyro implementation, all the model parameters are considered together.

This is coming up because I am, in the end, attempting to implement the Riemann version. In the Pyro implementation, it learns a covariance matrix for the parameters by taking the values for each parameter and flattening them into a single vector. To integrate with our current code, I would need to take just the values for the parameter which comes first in the model. Actually implementing this would be a pain, since the data comes with named parameters, and I'm not sure how to figure out which is the 'first' one.

**Comment by SparklePigBang** [comment]
My understanding is that the dataset is contained in all the parameters. In other words, the parameters are like different features of the data (except that they can be vectors themselves)

**Comment by SparklePigBang** [comment]
This seems to be the way that the Pyro implementation treats it

**Comment by SparklePigBang** [comment]
I should say, the parameters which are input into the model (not the latent ones). Comparing for example with the [Pyro implementation of HMC](https://github.com/pyro-ppl/pyro/blob/b64c15e2c2c1b94897c90aa032cf7156ca3ff531/pyro/infer/mcmc/hmc.py#L322), this would mean subsampling each value in the dictionary `z` of parameters, rather than just one of them.

**Comment by sacktock** [comment]
Yeah ok I understand what you mean so currently, say we have batch size 5 and dimension 5 then data could be a 5x5 matrix / tensor whatever and it would subsample each of these parameters, I am working on a commit where you can specify which positional arguments to subsample (default is the 1st positional argument at position 0), have a look once I push and see if you're happy.

**Comment by sacktock** [comment]
Going to close this now I think its resolved
